### ISSUE TITLE
Special return on no-rebuild

### ISSUE THREAD

**Issue by zimbatm** [Mic92/nix-build-uncached#28]
I have a use-case where I want to only run a command if nix-build-uncached has rebuilt something.

Basically:
* rebuild=$(nix-build-uncached)
* `if $rebuild; then cabal build; fi`

Potential implementations:
* reserve a special exit status that is returned on no-rebuild, IFF a special flag is also passed to nix-build-uncached. Eg: `--status`. Does this have the risk of having collisions with other types of build errors?
* write to a file. `nix-build-uncache --status ./file`

**Comment by Mic92** [comment]
Would this work for you?

```console
$ nix-build-uncached -build-flags '--out-link results/links'
$ rebuilds=$(find results -type l | wc -l)
$ if [[ $rebuild != 0 ]]; then cabal build; fi
```

**Comment by zimbatm** [comment]
Brilliant. Why didn't I think about this.

**Comment by zimbatm** [comment]
In GitHub Actions it should work something like this:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: cachix/install-nix-action@v11
      - name: nix-build
        id: nix-build
        run: |
          nix-build-uncached -build-flags '--out-link results/links'
          echo "::set-output name=rebuilds::$(find results -type l | wc -l)"
      - name: cabal build
        if: "${{ steps.nix-build.outputs.rebuilds }} != 0"
        run: cabal build
```
